# Generated by Django 4.0.1 on 2024-01-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_teacher'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assign_students',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assign_students',
            field=models.ManyToManyField(to='app.Student'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.BooleanField(choices=[('done', 'done'), ('pending', 'pending')]),
        ),
    ]
