# Generated by Django 4.0.1 on 2024-01-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_remove_assignment_assign_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('done', 'done'), ('pending', 'pending')], max_length=50),
        ),
    ]
