# Generated by Django 4.0.1 on 2024-01-08 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_assignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_desc',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
