# Generated by Django 4.0.1 on 2024-01-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_teacher'),
        ('teacher', '0004_assignment_assignment_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assign_students',
            field=models.ManyToManyField(blank=True, null=True, to='app.Student'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('pending', 'Pending')], max_length=50),
        ),
    ]
