# Generated by Django 4.0.1 on 2024-01-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_alter_assignment_assign_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_file',
            field=models.FileField(null=True, upload_to='docs/'),
        ),
    ]
