# Generated by Django 4.0.1 on 2024-01-02 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=250)),
                ('phone', models.CharField(max_length=10)),
                ('college', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('profile_pic', models.ImageField(upload_to='student')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
            ],
        ),
    ]
