# Generated by Django 4.0.1 on 2024-01-12 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0005_student_password'),
        ('teacher', '0006_alter_assignment_assignment_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_doc', models.FileField(upload_to='studentdoc/')),
                ('comment', models.TextField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.assignment')),
                ('associated_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teacher')),
            ],
        ),
    ]
